### ISSUE TITLE
How to run in Insert mode

### ISSUE THREAD

**Issue by shiro-saber** [chrisbra/changesPlugin#15]
Hi.
I only want to know, if it's possible mark the changes without leaving insert mode.

Cheers

**Comment by chrisbra** [comment]
Hi Shiro!

On Do, 26 Nov 2015, Shiro wrote:

> I only want to know, if it's possible mark the changes without leaving insert mode.

Well, if you do
    :let g:changes_fast = 1
Pressing <CR> in insert mode will add '+' signs. They will be correctly 
updated once insert mode is left so that the diff can be recalculated.
(this would otherwise be too slow for insert mode).

Is that what you want to know?

Best,
Christian
-- 
Mit einem freundlichen Wort und einer Pistole kann man mehr erreichen,
als nur mit einem freundlichen Wort.
		-- Al Capone

**Comment by shiro-saber** [comment]
Thanks chrisbra.

It's more or less that I wan't to know, but the thing it's that I want the plugin update signs each enter on the insert mode, not only when a new line is created, It's possible?

Cheers

**Comment by chrisbra** [comment]
Hi Shiro!

On Do, 26 Nov 2015, Shiro wrote:

> It's more or less that I wan't to know, but the thing it's that I want the plugin update signs each enter on the insert mode, not only when a new line is created, It's possible?

I don't understand. What is the difference between pressing Enter in 
insert mode and "not only when a new line is created"?
-- 
Ordnung und Unordnung kann man lernen, es ist Gewohnheit.
		-- Jean Paul
